"use client";

import { useState, useMemo } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { formatTime, formatDate } from "@/lib/utils";
import {
  TIMELINE_CATEGORY_ORDER,
  TIMELINE_CATEGORY_LABELS,
  TIMELINE_CATEGORY_COLORS,
  TIMELINE_CATEGORY_ICONS,
  formatDuration,
  calcDurationMinutes,
  calcGapMinutes,
  type TimelineCategory,
} from "@/lib/timeline-constants";
import {
  deleteTimelineEventAction,
  seedTemplateAction,
} from "@/lib/actions/timeline";
import AddTimelineEventDialog, {
  type TimelineEventRow,
} from "@/components/dashboard/AddTimelineEventDialog";
import Button from "@/components/ui/Button";

// ── Types & variants ────────────────────────────────────────────────────────

interface TimelineClientProps {
  weddingId:     string;
  weddingDate:   Date;
  partner1Name:  string;
  partner2Name:  string;
  initialEvents: TimelineEventRow[];
}

const containerVariants = {
  hidden: {},
  show:   { transition: { staggerChildren: 0.06 } },
};

const itemVariants = {
  hidden: { opacity: 0, x: 20, scale: 0.97 },
  show:   {
    opacity: 1, x: 0, scale: 1,
    transition: { type: "spring" as const, stiffness: 250, damping: 28 },
  },
};

// ── Print View ─────────────────────────────────────────────────────────────

function TimelinePrintView({
  events,
  partner1Name,
  partner2Name,
  weddingDate,
  onClose,
}: {
  events:       TimelineEventRow[];
  partner1Name: string;
  partner2Name: string;
  weddingDate:  Date;
  onClose:      () => void;
}) {
  return (
    <div className="fixed inset-0 bg-white z-50 overflow-auto">
      {/* Controls — hidden when printing */}
      <div className="print:hidden fixed top-4 right-4 flex gap-2 z-10">
        <button
          onClick={() => window.print()}
          className="px-4 py-2 bg-gray-900 text-white text-sm font-medium rounded-lg hover:bg-gray-700 transition-colors"
        >
          Print
        </button>
        <button
          onClick={onClose}
          className="px-4 py-2 bg-gray-100 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-200 transition-colors"
        >
          Close
        </button>
      </div>

      <div className="max-w-2xl mx-auto px-8 py-12">
        {/* Header */}
        <div className="mb-8 pb-6 border-b border-gray-200">
          <h1 className="font-serif text-3xl text-gray-900 mb-1">
            {partner1Name} &amp; {partner2Name}&apos;s Wedding Day
          </h1>
          <p className="text-gray-500">{formatDate(weddingDate)}</p>
        </div>

        {/* Events */}
        <div className="space-y-4">
          {events.map((evt) => {
            const color = TIMELINE_CATEGORY_COLORS[evt.category as TimelineCategory] ?? "#6b7280";
            const icon  = TIMELINE_CATEGORY_ICONS[evt.category as TimelineCategory] ?? "📋";
            const label = TIMELINE_CATEGORY_LABELS[evt.category as TimelineCategory] ?? evt.category;
            const dur   = evt.endTime
              ? calcDurationMinutes(evt.startTime, evt.endTime)
              : null;

            return (
              <div key={evt.id} className="flex gap-6 py-3 border-b border-gray-100 last:border-0">
                {/* Time */}
                <div className="w-24 shrink-0 text-sm text-gray-500 pt-0.5">
                  {formatTime(evt.startTime)}
                  {evt.endTime && (
                    <div className="text-gray-400">{formatTime(evt.endTime)}</div>
                  )}
                </div>

                {/* Details */}
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span
                      className="inline-flex items-center gap-1 text-[11px] font-medium px-2 py-0.5 rounded-full"
                      style={{ backgroundColor: `${color}18`, color }}
                    >
                      {icon} {label}
                    </span>
                    {dur !== null && (
                      <span className="text-[11px] text-gray-400">{formatDuration(dur)}</span>
                    )}
                  </div>
                  <p className="text-[15px] font-semibold text-gray-900">{evt.title}</p>
                  {evt.location   && <p className="text-sm text-gray-500 mt-0.5">📍 {evt.location}</p>}
                  {evt.assignedTo && <p className="text-sm text-gray-500">👤 {evt.assignedTo}</p>}
                  {evt.notes      && <p className="text-sm text-gray-400 mt-1 italic">{evt.notes}</p>}
                </div>
              </div>
            );
          })}
        </div>

        <p className="mt-10 text-xs text-gray-300 print:hidden">Generated by Vows</p>
      </div>
    </div>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────

export default function TimelineClient({
  weddingId,
  weddingDate,
  partner1Name,
  partner2Name,
  initialEvents,
}: TimelineClientProps) {
  const router = useRouter();

  const [events,           setEvents]           = useState<TimelineEventRow[]>(initialEvents);
  const [activeCategories, setActiveCategories] = useState<Set<string>>(
    () => new Set<string>(TIMELINE_CATEGORY_ORDER)
  );
  const [dialogOpen,    setDialogOpen]    = useState(false);
  const [editingEvent,  setEditingEvent]  = useState<TimelineEventRow | null>(null);
  const [printMode,     setPrintMode]     = useState(false);
  const [seedLoading,   setSeedLoading]   = useState(false);
  const [expandedNotes, setExpandedNotes] = useState<Set<string>>(new Set());
  const [deletingId,    setDeletingId]    = useState<string | null>(null);

  // ── Computed ───────────────────────────────────────────────────────────

  const sortedEvents = useMemo(
    () => [...events].sort((a, b) => a.startTime.localeCompare(b.startTime)),
    [events]
  );

  const visibleEvents = useMemo(
    () => sortedEvents.filter((e) => activeCategories.has(e.category)),
    [sortedEvents, activeCategories]
  );

  const stats = useMemo(() => {
    if (sortedEvents.length === 0) return null;
    const first    = sortedEvents[0];
    const last     = sortedEvents[sortedEvents.length - 1];
    const lastTime = last.endTime ?? last.startTime;
    const totalMin = (new Date(lastTime).getTime() - new Date(first.startTime).getTime()) / 60000;
    const hours    = Math.floor(totalMin / 60);
    const mins     = Math.round(totalMin % 60);
    const hoursStr = mins > 0 ? `${hours} hr ${mins} min` : `${hours} hr`;

    return {
      totalEvents: sortedEvents.length,
      hoursPlanned: hoursStr,
      startsAt: formatTime(first.startTime),
      endsAt:   formatTime(lastTime),
    };
  }, [sortedEvents]);

  const annotations = useMemo(() => {
    const result = new Map<string, { gap: number | null; overlap: boolean }>();
    for (let i = 0; i < visibleEvents.length - 1; i++) {
      const a   = visibleEvents[i];
      const b   = visibleEvents[i + 1];
      const gap = calcGapMinutes(a.endTime, b.startTime);
      result.set(a.id, {
        gap,
        overlap: gap !== null && gap < 0,
      });
    }
    return result;
  }, [visibleEvents]);

  const distinctDays = useMemo(() => {
    const days = new Set<string>(sortedEvents.map((e) => e.startTime.slice(0, 10)));
    return Array.from(days).sort();
  }, [sortedEvents]);

  // ── Handlers ───────────────────────────────────────────────────────────

  function toggleCategory(cat: string) {
    setActiveCategories((prev) => {
      const next = new Set(prev);
      // If all are active, clicking one → filter to only that one
      if (next.size === TIMELINE_CATEGORY_ORDER.length) {
        return new Set<string>([cat]);
      }
      // If this is the only active one, clicking it → restore all
      if (next.size === 1 && next.has(cat)) {
        return new Set<string>(TIMELINE_CATEGORY_ORDER);
      }
      if (next.has(cat)) next.delete(cat);
      else next.add(cat);
      return next;
    });
  }

  function toggleAllCategories() {
    setActiveCategories(new Set<string>(TIMELINE_CATEGORY_ORDER));
  }

  async function handleSeedTemplate() {
    setSeedLoading(true);
    try {
      await seedTemplateAction();
      router.refresh();
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to load template.");
    } finally {
      setSeedLoading(false);
    }
  }

  async function handleDelete(id: string) {
    if (!confirm("Remove this event from the timeline?")) return;
    setDeletingId(id);
    try {
      await deleteTimelineEventAction(id);
      setEvents((prev) => prev.filter((e) => e.id !== id));
    } catch {
      alert("Failed to delete event.");
    } finally {
      setDeletingId(null);
    }
  }

  function handleEventSaved(saved: TimelineEventRow) {
    setEvents((prev) => {
      const idx = prev.findIndex((e) => e.id === saved.id);
      if (idx >= 0) {
        const next = [...prev];
        next[idx] = saved;
        return next;
      }
      return [...prev, saved];
    });
  }

  function handleOpenAdd() {
    setEditingEvent(null);
    setDialogOpen(true);
  }

  function handleOpenEdit(evt: TimelineEventRow) {
    setEditingEvent(evt);
    setDialogOpen(true);
  }

  function toggleNotes(id: string) {
    setExpandedNotes((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  // ── Print mode ─────────────────────────────────────────────────────────

  if (printMode) {
    return (
      <TimelinePrintView
        events={sortedEvents}
        partner1Name={partner1Name}
        partner2Name={partner2Name}
        weddingDate={weddingDate}
        onClose={() => setPrintMode(false)}
      />
    );
  }

  // ── Empty state ────────────────────────────────────────────────────────

  if (events.length === 0) {
    return (
      <>
        <div className="flex flex-col items-center justify-center bg-white rounded-xl shadow-apple-sm px-8 py-20 text-center">
          <div className="text-6xl mb-6">✨</div>
          <h2 className="font-serif text-2xl text-gray-800 mb-2">
            Your day, beautifully organized
          </h2>
          <p className="text-sm text-gray-400 max-w-xs mb-8">
            Add your first event or load our default wedding day template to get started.
          </p>
          <div className="flex flex-col sm:flex-row gap-3">
            <Button
              variant="secondary"
              size="md"
              onClick={handleSeedTemplate}
              loading={seedLoading}
            >
              ✨ Load default template
            </Button>
            <Button variant="primary" size="md" onClick={handleOpenAdd}>
              + Add first event
            </Button>
          </div>
        </div>

        <AddTimelineEventDialog
          open={dialogOpen}
          onOpenChange={setDialogOpen}
          editingEvent={editingEvent}
          weddingDate={weddingDate}
          onSuccess={handleEventSaved}
        />
      </>
    );
  }

  // ── Full timeline view ─────────────────────────────────────────────────

  const allActive = activeCategories.size === TIMELINE_CATEGORY_ORDER.length;

  return (
    <>
      {/* Stats bar */}
      {stats && (
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-8">
          {[
            { label: "Total events",   value: String(stats.totalEvents) },
            { label: "Hours planned",  value: stats.hoursPlanned },
            { label: "Starts at",      value: stats.startsAt },
            { label: "Ends at",        value: stats.endsAt },
          ].map((s) => (
            <div key={s.label} className="bg-white rounded-lg shadow-apple-sm p-4">
              <p className="text-xs text-gray-400 font-medium uppercase tracking-wider">{s.label}</p>
              <p className="text-xl font-semibold text-gray-900 mt-1">{s.value}</p>
            </div>
          ))}
        </div>
      )}

      {/* Controls row */}
      <div className="flex flex-wrap items-center gap-3 mb-6">
        {/* Category filter chips */}
        <div className="flex flex-wrap gap-2 flex-1">
          <button
            type="button"
            onClick={toggleAllCategories}
            className={cn(
              "flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all duration-150 border",
              allActive
                ? "bg-gray-900 text-white border-transparent"
                : "border-gray-200 bg-gray-50 text-gray-500 hover:bg-gray-100"
            )}
          >
            All
          </button>
          {TIMELINE_CATEGORY_ORDER.map((cat) => {
            const color    = TIMELINE_CATEGORY_COLORS[cat];
            const icon     = TIMELINE_CATEGORY_ICONS[cat];
            const label    = TIMELINE_CATEGORY_LABELS[cat];
            const isActive = !allActive && activeCategories.has(cat);
            return (
              <button
                key={cat}
                type="button"
                onClick={() => toggleCategory(cat)}
                className={cn(
                  "flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all duration-150 border",
                  isActive
                    ? "border-transparent text-white shadow-sm"
                    : "border-gray-200 bg-gray-50 text-gray-500 hover:bg-gray-100"
                )}
                style={isActive ? { backgroundColor: color } : undefined}
              >
                <span>{icon}</span>
                <span>{label}</span>
              </button>
            );
          })}
        </div>

        {/* Action buttons */}
        <div className="flex gap-2 shrink-0">
          <button
            type="button"
            onClick={() => setPrintMode(true)}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-gray-200 bg-white text-xs font-medium text-gray-600 hover:bg-gray-50 transition-colors shadow-apple-xs"
          >
            🖨️ Print / Share
          </button>
          <Button variant="primary" size="sm" onClick={handleOpenAdd}>
            + Add event
          </Button>
        </div>
      </div>

      {/* Multi-day filter — only if events span multiple days */}
      {distinctDays.length > 1 && (
        <div className="flex gap-2 mb-6">
          {distinctDays.map((day) => (
            <button
              key={day}
              type="button"
              className="px-3 py-1.5 rounded-lg border border-gray-200 bg-white text-xs font-medium text-gray-600 hover:bg-gray-50 transition-colors"
            >
              {formatDate(day)}
            </button>
          ))}
        </div>
      )}

      {/* Timeline body */}
      {visibleEvents.length === 0 ? (
        <div className="bg-white rounded-xl shadow-apple-sm p-12 text-center">
          <p className="text-gray-400 text-sm">No events match the selected filters.</p>
          <button
            type="button"
            onClick={toggleAllCategories}
            className="mt-3 text-sm text-accent hover:underline"
          >
            Show all categories
          </button>
        </div>
      ) : (
        <div className="relative">
          {/* Gold connector line — spans full height of the timeline */}
          <div
            aria-hidden
            className="absolute left-[88px] top-0 bottom-0 w-[2px] pointer-events-none"
            style={{
              background: "linear-gradient(to bottom, transparent 0%, #c9a84c 8%, #c9a84c 92%, transparent 100%)",
            }}
          />

          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="show"
            className="space-y-4"
          >
            {visibleEvents.map((evt, idx) => {
              const color     = TIMELINE_CATEGORY_COLORS[evt.category as TimelineCategory] ?? "#6b7280";
              const icon      = TIMELINE_CATEGORY_ICONS[evt.category as TimelineCategory] ?? "📋";
              const label     = TIMELINE_CATEGORY_LABELS[evt.category as TimelineCategory] ?? evt.category;
              const dur       = evt.endTime ? calcDurationMinutes(evt.startTime, evt.endTime) : null;
              const ann       = annotations.get(evt.id);
              const isDeleting = deletingId === evt.id;
              const notesExpanded = expandedNotes.has(evt.id);

              return (
                <motion.div key={evt.id} variants={itemVariants}>
                  {/* Event row — 3-column grid */}
                  <div className="grid items-start" style={{ gridTemplateColumns: "64px 48px 1fr" }}>
                    {/* Col 1: Time label */}
                    <div className="pt-4 text-right pr-3">
                      <span className="text-xs font-medium text-gray-400 leading-none">
                        {formatTime(evt.startTime)}
                      </span>
                    </div>

                    {/* Col 2: Node circle (centered on the line) */}
                    <div className="flex justify-center pt-[14px]">
                      <div
                        className="w-3 h-3 rounded-full border-2 bg-white shadow-apple-xs z-10 relative shrink-0"
                        style={{ borderColor: color }}
                      />
                    </div>

                    {/* Col 3: Event card */}
                    <motion.div
                      whileHover={{ scale: 1.01 }}
                      whileTap={{ scale: 0.97 }}
                      className={cn(
                        "bg-white rounded-lg shadow-apple-sm overflow-hidden group transition-opacity",
                        isDeleting && "opacity-50 pointer-events-none"
                      )}
                      style={{ borderTop: `4px solid ${color}` }}
                    >
                      {/* Card header */}
                      <div className="flex items-start justify-between p-4 pb-2">
                        <div className="flex-1 min-w-0">
                          {/* Category chip */}
                          <span
                            className="inline-flex items-center gap-1 text-[11px] font-medium px-2 py-0.5 rounded-full mb-2"
                            style={{ backgroundColor: `${color}18`, color }}
                          >
                            {icon} {label}
                          </span>

                          {/* Title */}
                          <h3 className="text-[15px] font-semibold text-gray-900 leading-snug">
                            {evt.title}
                          </h3>

                          {/* Time range + duration */}
                          <div className="flex items-center flex-wrap gap-2 mt-1.5">
                            <span className="text-sm text-gray-500">{formatTime(evt.startTime)}</span>
                            {evt.endTime && (
                              <>
                                <span className="text-gray-300 text-sm">→</span>
                                <span className="text-sm text-gray-500">{formatTime(evt.endTime)}</span>
                                {dur !== null && (
                                  <span
                                    className="text-[11px] font-medium text-white px-2 py-0.5 rounded-full"
                                    style={{ backgroundColor: color }}
                                  >
                                    {formatDuration(dur)}
                                  </span>
                                )}
                              </>
                            )}
                          </div>
                        </div>

                        {/* Edit / Delete — slide in on hover */}
                        <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity ml-3 shrink-0 pt-0.5">
                          <button
                            type="button"
                            onClick={() => handleOpenEdit(evt)}
                            className="w-7 h-7 flex items-center justify-center rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors"
                            title="Edit event"
                          >
                            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                              <path strokeLinecap="round" strokeLinejoin="round" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                            </svg>
                          </button>
                          <button
                            type="button"
                            onClick={() => handleDelete(evt.id)}
                            className="w-7 h-7 flex items-center justify-center rounded-md text-gray-400 hover:text-red-500 hover:bg-red-50 transition-colors"
                            title="Delete event"
                          >
                            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                              <path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                          </button>
                        </div>
                      </div>

                      {/* Location */}
                      {evt.location && (
                        <div className="flex items-center gap-1.5 px-4 pb-2 text-xs text-gray-500">
                          <span>📍</span>
                          <span>{evt.location}</span>
                        </div>
                      )}

                      {/* Assigned to */}
                      {evt.assignedTo && (
                        <div className="flex items-center gap-1.5 px-4 pb-2 text-xs text-gray-500">
                          <span>👤</span>
                          <span>{evt.assignedTo}</span>
                        </div>
                      )}

                      {/* Notes — collapsible */}
                      {evt.notes && (
                        <div className="px-4 pb-3">
                          <p className={cn(
                            "text-xs text-gray-400 leading-relaxed",
                            !notesExpanded && "line-clamp-2"
                          )}>
                            {evt.notes}
                          </p>
                          {evt.notes.length > 100 && (
                            <button
                              type="button"
                              onClick={() => toggleNotes(evt.id)}
                              className="text-[11px] text-accent mt-1 hover:underline"
                            >
                              {notesExpanded ? "Show less" : "Show more"}
                            </button>
                          )}
                        </div>
                      )}
                    </motion.div>
                  </div>

                  {/* Gap / overlap indicator between events */}
                  {ann && idx < visibleEvents.length - 1 && (
                    <AnimatePresence>
                      {ann.overlap && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: "auto" }}
                          exit={{ opacity: 0, height: 0 }}
                          className="ml-[112px] mt-2"
                        >
                          <div className="flex items-center gap-1.5 bg-red-50 border border-red-200 rounded-md px-3 py-1.5 text-xs text-red-600">
                            ⚠️ These events overlap
                          </div>
                        </motion.div>
                      )}
                      {!ann.overlap && ann.gap !== null && ann.gap > 60 && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: "auto" }}
                          exit={{ opacity: 0, height: 0 }}
                          className="ml-[112px] mt-2"
                        >
                          <div className="flex items-center gap-1.5 bg-amber-50 border border-amber-200 rounded-md px-3 py-1.5 text-xs text-amber-700">
                            ⏱ {formatDuration(ann.gap)} gap
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  )}
                </motion.div>
              );
            })}
          </motion.div>
        </div>
      )}

      {/* Add event button at bottom */}
      <div className="mt-8 flex justify-center">
        <button
          type="button"
          onClick={handleOpenAdd}
          className="flex items-center gap-2 px-5 py-3 rounded-xl border-2 border-dashed border-gray-200 text-sm text-gray-400 hover:border-accent hover:text-accent transition-colors"
        >
          + Add another event
        </button>
      </div>

      {/* Dialog */}
      <AddTimelineEventDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        editingEvent={editingEvent}
        weddingDate={weddingDate}
        onSuccess={handleEventSaved}
      />
    </>
  );
}
